
import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';

class GlobalErrorBoundary extends React.Component<{children: React.ReactNode}, {error: any}> {
  constructor(props: any) { super(props); this.state = { error: null }; }
  static getDerivedStateFromError(error: any) { return { error }; }
  render() {
    if (this.state.error) {
      return (
        <div style={{ padding: '20px', color: 'red', fontFamily: 'monospace', whiteSpace: 'pre-wrap' }}>
          <h2>Application Crashed</h2>
          {String(this.state.error.stack || this.state.error)}
        </div>
      );
    }
    return this.props.children;
  }
}

const rootElement = document.getElementById('root');
if (!rootElement) throw new Error("Root element not found");

const root = ReactDOM.createRoot(rootElement);
root.render(
  <GlobalErrorBoundary>
    <App />
  </GlobalErrorBoundary>
);

// Register Service Worker for Offline Browser Access (PWA)
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    // Note: sw.js must exist in public/ or be generated by build process
    navigator.serviceWorker.register('/sw.js').then(reg => {
      console.log('PWA Service Worker registered.', reg.scope);
    }).catch(err => {
      console.error('PWA registration failed:', err);
    });
  });
}
